#BBNBI_convert.py
 
"""
Samuel Ward
18/04/2019
----
converts BBNBI deposition to LOCUST deposition for MAST study
---
usage:
 
notes:         
    
---
"""

import context
from classes.input_classes.beam_deposition import Beam_Deposition as bd
from classes.input_classes.equilibrium import Equilibrium as equi
import processing.utils
from constants import *
import pathlib
import support

#set up all the file paths
filename_BBNBI_FO=pathlib.Path('ASCOT') / '29034W03' / 'mast_29034_360ms_injSS_BBNBI_ward.particles'
filename_eq=pathlib.Path('LOCUST') / '29034W03' / 'g29034'

#generate full orbit BBNBI deposition list
#eq=equi('',data_format='GEQDSK',filename=filename_eq,GEQDSKFIX=1)
#mybd=bd('',data_format='ASCOT_FO',filename=filename_BBNBI_FO)
#mybd.set(V_pitch=processing.utils.pitch_calc_2D(mybd,eq))
#mybd.set(E=0.5*species_mass*(mybd['V_R']**2+mybd['V_Z']**2+mybd['V_tor']**2)/charge_e)
#mybd.dump_data(data_format='LOCUST_FO_weighted',filename=shot_time_path / 'ptcles.dat_BBNBI_weighted_FO')
#mybd.dump_data(data_format='LOCUST_FO',filename=shot_time_path / 'ptcles.dat_BBNBI_FO')
#mybd.dump_data(data_format='ASCOT_FO',filename=shot_time_path / 'input.particles_BBNBI_FO',equilibrium=eq)

#generate guiding centre deposition list from guiding centre data generated by an ASCOT simulation and stored in inistate

filename_BBNBI_GC=list((support.dir_output_files / 'ASCOT' / '29034W03' / 'BBNBI_birth_GC' / '2D_10_freia').glob('*.h5'))[0].parts[-1]
filename_BBNBI_GC=pathlib.Path('ASCOT') / '29034W03' / 'BBNBI_birth_GC' / '2D_10_freia' / filename_BBNBI_GC

mybd_FO=bd('',data_format='ASCOT_FO_h5_ini',filename=filename_BBNBI_GC)
mybd_GC=bd('',data_format='ASCOT_GC_h5_ini',filename=filename_BBNBI_GC)

mybd_FO.look()
mybd_GC.look()

mybd_GC.plot(real_scale=True,number_bins=400)

#CHECK PITCH DEFINITION HERE
#should be negative for LOCUST since parallel to field but antiparallel to current

#mybd.dump_data(data_format='LOCUST_GC_weighted',filename=shot_time_path / 'ptcles.dat_BBNBI_weighted_GC_reduced')