#!/bin/bash 
#or /usr/bin/env bash

########################## users set this top level
#run info
tokamak='DIII-D'
#LOCUST input files in LOCUST_IO
LOCUST_input_equilibrium='g157418.03000'
LOCUST_input_profile_ne='profile_ne.dat'
LOCUST_input_profile_Te='profile_Te.dat'
LOCUST_input_profile_Ti='profile_Ti.dat'
LOCUST_input_mesh='test.mesh.inp_ANSYS'
LOCUST_input_ptcles='ptcles.dat'
LOCUST_input_collisions='collisions.dat'


##########################
#prepare i/o
dir_this_script="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #get current working directory (cannot use pwd as this is invoking shell's pwd - not script pwd)
dir_locust_io="$(dirname "$dir_this_script")"
dir_input_files=${dir_locust_io}/input_files
dir_output_files=${dir_locust_io}/output_files
dir_cache_files=${dir_locust_io}/cache_files
dir_LOCUST=${dir_locust_io}/LOCUST

mkdir -p "/tmp/${USER}/locust.${tokamak}/InputFiles/" #create the folder structure if not there already
mkdir -p "/tmp/${USER}/locust.${tokamak}/OutputFiles/" #create the folder structure if not there already
mkdir -p "/tmp/${USER}/locust.${tokamak}/CacheFiles/" #create the folder structure if not there already

#AT THIS POINT JUST LINK BLANK FILES IN /TMP TO THE FILES IN LOCUST_IO TO MAKE IT RUN

ln -s "${dir_input_files}/${LOCUST_input_equilibrium}" "/tmp/${USER}/locust.${tokamak}/InputFiles/g157418.03000" #symlink LOCUST to data stored in LOCUST_IO
ln -s "${dir_input_files}/${LOCUST_input_profile_ne}" "/tmp/${USER}/locust.${tokamak}/InputFiles/profile_ne.dat"
ln -s "${dir_input_files}/${LOCUST_input_profile_Te}" "/tmp/${USER}/locust.${tokamak}/InputFiles/profile_Te.dat"
ln -s "${dir_input_files}/${LOCUST_input_profile_Ti}" "/tmp/${USER}/locust.${tokamak}/InputFiles/profile_Ti.dat"
ln -s "${dir_input_files}/${LOCUST_input_mesh}" "/tmp/${USER}/locust.${tokamak}/InputFiles/test.mesh.inp_ANSYS" 
ln -s "${dir_input_files}/${LOCUST_input_ptcles}"  "/tmp/${USER}/locust.${tokamak}/InputFiles/ptcles.dat" 
ln -s "${dir_input_files}/${LOCUST_input_collisions}" "/tmp/${USER}/locust.${tokamak}/InputFiles/collisions.dat"

#LOCUST output
ln -s "${dir_output_files}/" "/tmp/${USER}/locust.${tokamak}/OutputFiles/"  

#LOCUST cache
ln -s "${dir_cache_files}/" "/tmp/${USER}/locust.${tokamak}/CacheFiles/" 
##########################
#compile
FLAGS="'$*'"
(cd ${dir_LOCUST} && make clean && make "FLAGS=$FLAGS")
##########################
#run
export OMP_NUM_THREADS=1
export OMP_STACKSIZE=102400
export NO_AT_BRIDGE=1
ulimit -s 2000000
(cd ${dir_LOCUST} && exec locust)







#NOTES:
#-usual lOCUST directories in /tmp must not exist for symlinks to work

#USAGE:
#./locust_run -Dsome_flag -Danother_flag