#!/bin/bash
#SBATCH --job-name=LOCUST
#SBATCH --gres=gpu:kepler:1
#SBATCH --partition=gpus
#SBATCH --cpus-per-task=1
#SBATCH --mail-user samuel.ward@york.ac.uk 
#SBATCH --mail-type=END,FAIL,TIME_LIMIT
#SBATCH -o LOCUST_SLURM.out
#SBATCH -e LOCUST_SLURM.err

#get time and date 
date_time=$(date +'%d-%m--%Y:%H:%M:%S')


#compile environment
#source LOCUST_env
module purge
module load pgf/18.3 #load compilers + HDF for output
module load hdf5/1.8.19-mpich3.2-pgf18.3
module load cuda/9.0
module unload gcc7/default
export FFLAGS="-I$HDF5_DIR/include" #set up some variables to point makefile to PGfortran/CUDA compiler HDF5-linker libraries
export LDFLAGS="-L$HDF5_DIR/lib"

#compile
#FLAGS_USER='-DTOKAMAK=8 -DBRELAX -DUNBOR=100 -DOPENMESH -DOPENTRACK -DPFCMOD -DTOKHEAD -DTIMAX=0.0001D0 -DSTDOUT -DGEQDSKFIX1'
#make clean
#make FLAGS="{$FLAGS_USER}"

#run-time environment
export OMP_NUM_THREADS=1
export OMP_STACKSIZE=102400
export NO_AT_BRIDGE=1
ulimit -s 2000000

#run
./locust


#USAGE:
#sbatch LOCUST_SLURM

#NOTE:
#currently needs compiling manually