#perturbation_check.py
"""
Samuel Ward
15/08/2019
----
see what the perturbations generated by MARS-F look like
---
usage:
 
notes:         
---
"""

import context
from classes.input_classes.perturbation import Perturbation
import pathlib
import support

mode_number=2
perturbation_filename=support.dir_input_files / 'LOCUST' / '3D_field_scan' / 'BPLASMA_n{}_160.0_resist_resp.dat'.format(str(mode_number))
perturbation=Perturbation(ID='',data_format='LOCUST',n=mode_number)
perturbation.plot_components(R,Z,phi,phase=0,i3dr=1,LCFS=False,limiters=False,number_bins=50,vminmax=None,absolute=False)