#!/bin/bash
#SBATCH --job-name=LOCUST
#SBATCH --gres=gpu:8 
#SBATCH --partition=gpu_p100_titan
#SBATCH --cpus-per-task=1
#SBATCH --mail-user samuel.ward@iter.org 
#SBATCH --mail-type=END,FAIL,TIME_LIMIT
#SBATCH -o LOCUST_SLURM.out
#SBATCH -e LOCUST_SLURM.err

#get time and date 
date_time=$(date +'%d-%m--%Y:%H:%M:%S')


#compile environment
#source LOCUST_env
. ~/.bashrc
. ~/installed_programs/LOCUST/LOCUST.env

echo $SLURM_JOB_USER
echo $userid

#run
./locust 


#USAGE:
#sbatch LOCUST_SLURM

#NOTE:
#currently needs compiling manually